###

GET http://localhost:8080/movies/all

###

POST http://localhost:8080/movies/
Content-Type: application/json

{
  "title": "bbb",
  "genre": "Crime",
  "duration": 175,
  "rating": 9.2,
  "releaseYear": 1972
}

###

PUT http://localhost:8080/movies/update/bbb
Content-Type: application/json

{
  "title": "AAAAAAAA",
  "genre": "Crime",
  "duration": 175,
  "rating": 9.2,
  "releaseYear": 1972
}

###
DELETE http://localhost:8080/movies/AAAAAAAA

###
DELETE http://localhost:8080/movies/
